osx_image: xcode7.3

dist: trusty
sudo: required

notifications:
  email:
    on_success: never
    on_failure: change

matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - icnsutils
      - graphicsmagick
      - xz-utils

language: c

cache:
  timeout: 600
  directories:
    - node_modules
    - $HOME/.electron

install:
  - nvm install 7
  - npm prune
  - cd app && npm prune && cd ..
  - npm install

script:
  - npm run lint
  - npm run build:prod
  - npm run test:setup
  - npm test
  - npm run release

after_failure:
  - npm run test:review
